name: Local Nonsatiation
title: Local Nonsatiation
description: Description
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: Project Planning
    url: /plan
  - title: About
    url: /about
  - title: Contact
    url: /contact

email: anthony.hong@gmail.com
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id:


